# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
kind: Stack
metadata:
  name: stacked_model
spec:
  connection:
    transport:
      redispubsub:
        uri: redis://localhost:6379
        timeout: 60
  models:
    - name: simbus
      model:
        name: simbus
      channels:
        - name: test
          expectedModelCount: 2
    - name: stacked_one
      uid: 43
      model:
        name: StackedModelOne
      channels:
        - name: test
          alias: model_channel
    - name: stacked_two
      uid: 44
      model:
        name: StackedModelTwo
      channels:
        - name: test
          alias: model_channel
---
kind: Model
metadata:
  name: simbus
